name: tether_libs
description: "A library of Dart code for Tether, including database models, client managers, and more."
version: 1.0.5
repository: https://github.com/cspecter/tether_libs

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  logging: ^1.3.0
  meta: ^1.16.0
  recase: ^4.1.0
  rxdart: ^0.28.0
  sqlite_async: ^0.11.5
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
