name: tether_generators
description: "A command-line tool and builders for generating Supabase-related Dart code." # Updated description
version: 0.0.1
homepage: # Add your homepage if you have one

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
  postgres: ^3.5.6
  collection: ^1.19.1
  tether_libs:
    path: ../tether_libs
  inflection3: ^0.5.3+2
  recase: ^4.1.0
  path: ^1.9.1


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8

executables:
  tether: # This is the command users will type (e.g., `dart run tether_generators:tether` or `tether` if globally activated)
    # tether_gen # You can choose a different name if you prefer
