# supabase_gen configuration file

# Database connection details
database:
  host: localhost
  port: 54321
  database: postgres
  username: postgres
  password: password
  ssl: false

# General code generation settings
generation:
  output_directory: lib/database # Base directory for generated code (excluding assets)
  exclude_tables:
    - migrations
    - schema_migrations
  include_tables: []
  exclude_references: []
  generate_for_all_tables: true

  # --- Database Settings ---
  dbClassName: AppDb
  databaseName: 'app_db.sqlite'

  # --- Model Generation Settings ---
  models:
    enabled: true
    filename: models.g.dart # Or your preferred name
    prefix: ''
    suffix: Model
    use_null_safety: true

  # --- Supabase Select List Generation Settings ---
  supabase_selectors:
    enabled: true
    # filename: supabase_selectors.dart

  # --- Supabase Select BUILDER Generation Settings ---
  supabase_select_builders:
    enabled: true
    filename: supabase_select_builders.g.dart
    suffix: SelectBuilder

  # --- SQLite Migration Generation Settings (NEW) ---
  sqlite_migrations:
    enabled: true # Generate .sql migration files for sqlite_async
    # Directory relative to project root (often assets for bundling)
    output_subdir: 'sqlite_migrations'

  # --- ClientManager Generation Settings ---
  client_managers:
    enabled: true # Enable or disable ClientManager generation
    use_riverpod: true # Use Riverpod for state management (set to false for Provider)

  # --- Provider Generation Settings --- # <<< NEW SECTION
  providers:
    enabled: true # Assuming you might want an enabled flag later
    output_subdir: 'providers' # Subdirectory within output_directory

  # Endings to remove during sanitization
  sanitization_endings:
    - _id
    - _fk
    - _uuid
