name: tether
description: "A command-line tool and builders for generating Supabase-related Dart code."
version: 1.0.0
repository: https://github.com/cspecter/tether_libs

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
  postgres: ^3.5.6
  collection: ^1.19.1
  tether_libs: ^1.0.0
  inflection3: ^0.5.3+2
  recase: ^4.1.0
  path: ^1.9.1
  dotenv: ^4.2.0


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8

executables:
  tether:
    script: bin/tether.dart
