# supabase_gen configuration file

database:
  host: TETHER_SUPABASE_HOST # The hostname or IP address of your Supabase database.
  port: TETHER_SUPABASE_PORT # The port number for your Supabase database. Default Supabase is 5432, but local dev might use 54321 via Docker.
  database: TETHER_SUPABASE_DB_NAME # The name of the database to connect to (usually 'postgres' for Supabase).
  username: TETHER_SUPABASE_DB_USER # The username for connecting to the database (usually 'postgres' for Supabase).
  password: TETHER_SUPABASE_DB_PASSWORD # The password for the specified username. For local development, this might be a default. For production, use environment variables or a secure secrets manager.
  ssl: TETHER_SUPABASE_DB_SSL
generation:
  output_directory: lib/database
  model_prefix: ''
  model_suffix: Model
  repository_suffix: Repository
  exclude_tables: 
    # Exclude system schemas
    - '_realtime.*'
    - 'auth.*'
    - 'net.*'
    - 'pgsodium.*'
    - 'realtime.*'
    - 'storage.*'
    - 'supabase_functions.*'
    - 'vault.*'
  include_tables: 
    - 'public.*'
  exclude_references: 
  generate_for_all_tables: false  
  use_null_safety: true

  # --- Database Settings ---
  dbClassName: AppDb
  databaseName: 'app_db.sqlite'

  # --- Model Generation Settings ---
  models:
    enabled: true
    filename: models.g.dart # Or your preferred name
    prefix: ''
    suffix: Model
    use_null_safety: true

  # --- Supabase Select List Generation Settings ---
  supabase_selectors:
    enabled: true
    # filename: supabase_selectors.dart

  # --- Supabase Select BUILDER Generation Settings ---
  supabase_select_builders:
    enabled: true
    filename: supabase_select_builders.g.dart
    suffix: SelectBuilder

  # --- SQLite Migration Generation Settings (NEW) ---
  sqlite_migrations:
    enabled: true # Generate .sql migration files for sqlite_async
    # Directory relative to project root (often assets for bundling)
    output_subdir: 'sqlite_migrations'

  # --- ClientManager Generation Settings ---
  client_managers:
    enabled: true # Enable or disable ClientManager generation
    use_riverpod: true # Use Riverpod for state management (set to false for Provider)

  # --- Provider Generation Settings --- # <<< NEW SECTION
  providers:
    enabled: true # Assuming you might want an enabled flag later
    output_subdir: 'providers' # Subdirectory within output_directory

  # --- Authentication Settings ---
  # If your application uses Supabase authentication, you might want to include settings for generating
  # authentication-related classes and methods. This can include user profile management, session handling,
  authentication:
    # If true, the generator will create authentication-related classes and methods.
    enabled: true
    profile_table: 'profiles' # The name of the table that stores user profiles, like users or profiles.

  # --- Background Services Settings ---
  background_services:
  # If true, the generator will create background service-related classes and methods.
    enabled: true

  # Endings to remove during sanitization
  sanitization_endings:
    - _id
    - _fk
    - _uuid